### ISSUE TITLE
cannot open with python

### ISSUE THREAD

**Issue by mr2meowsYT** [RexScratch/sb3tosb2#4]
i downloaded the python zip file and extracted it but i cant open the .py file with python

**Comment by elliott867158** [comment]
Try using python 3

**Comment by PiotrGrochowski** [comment]
thanks it worked actually, even though I don't know programming

**Comment by elliott867158** [comment]
glad to hear it worked

**Comment by avs-7** [comment]
If issue is solved, please don't forget to close it.

**Comment by mr2meowsYT** [comment]
I forgor 💀 what this is and I have a different computer with a completely different operating system so ima close this issue
